---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: h1-finland-hub-monitor.crane-goldeye.ts.net
pushgateway_dns: h1-finland-hub-monitor.crane-goldeye.ts.net/pushgateway
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

amplifier:
  tofnd:
    source_url: https://github.com/axelarnetwork/tofnd/releases/download
    ports:
      default_port: 50051
  ampd:
    source_url: https://github.com/axelarnetwork/axelar-amplifier/releases/download
    ports:
      health_check_bind_addr: 3000
      grpc_port: 9090
      monitoring_server_bind_addr: 30001
  flow:
    source_url: https://github.com/axelarnetwork/axelar-amplifier/releases/download
    ports:
      monitoring_server_bind_addr: 30002
  xrplevm:
    source_url: https://github.com/axelarnetwork/axelar-amplifier/releases/download
    ports:
      monitoring_server_bind_addr: 30003
  plume:
    source_url: https://github.com/axelarnetwork/axelar-amplifier/releases/download
    ports:
      monitoring_server_bind_addr: 30004
  monad:
    source_url: https://github.com/axelarnetwork/axelar-amplifier/releases/download
    ports:
      monitoring_server_bind_addr: 30005
  berachain:
    source_url: https://github.com/axelarnetwork/axelar-amplifier/releases/download
    ports:
      monitoring_server_bind_addr: 30006
  hyperliquid:
    source_url: https://github.com/axelarnetwork/axelar-amplifier/releases/download
    ports:
      monitoring_server_bind_addr: 30007
  hedera:
    source_url: https://github.com/axelarnetwork/axelar-amplifier/releases/download
    ports:
      monitoring_server_bind_addr: 30008
  xrpl:
    source_url: https://github.com/axelarnetwork/axelar-amplifier/releases/download
    ports:
      monitoring_server_bind_addr: 30009
  sui:
    source_url: https://github.com/axelarnetwork/axelar-amplifier/releases/download
    ports:
      monitoring_server_bind_addr: 30010
  stellar:
    source_url: https://github.com/axelarnetwork/axelar-amplifier/releases/download
    ports:
      monitoring_server_bind_addr: 30011
  solana:
    source_url: https://github.com/axelarnetwork/axelar-amplifier/releases/download
    ports:
      monitoring_server_bind_addr: 30012

wasmvm:
  source_url: https://github.com/CosmWasm/wasmvm/releases/download
