---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

amplifier:
  tofnd:
    source_url: https://github.com/axelarnetwork/tofnd/releases/download
    ports:
      default_port: 50051
  ampd:
    source_url: https://github.com/axelarnetwork/axelar-amplifier/releases/download
    ports:
      health_check_bind_addr: 3000

wasmvm:
  source_url: https://github.com/CosmWasm/wasmvm/releases/download

axelar:
  vald:
    source_url: https://github.com/axelarnetwork/axelar-core/releases/download
  tofnd:
    source_url: https://github.com/axelarnetwork/tofnd/releases/download
    ports:
      default_port: 11450
