---
# maintains ports, bianry or repo urls

org: encapsulate

default_node_types:
  - validator
  - default

amplifier:
  tofnd:
    source_url: https://github.com/axelarnetwork/tofnd/releases/download
    ports:
      default_port: 50051
  ampd:
    source_url: https://github.com/axelarnetwork/axelar-amplifier/releases/download
    ports:
      health_check_bind_addr: 3000
