---
# maintains versions and can overwrite all.yml
amplifier:
  tofnd:
    version: v0.10.1
  ampd:
    version: v1.7.0
    vote_metrics_url: https://api.axelarscan.io/validator/searchVMPolls
  address: axelar1nppclnu328tgvxyvu0fmd6yder3r9mrrgusrj3
