---
# maintains versions and can overwrite all.yml
amplifier:
  tofnd:
    version: v1.0.1
  ampd:
    version: v1.14.2
    vote_metrics_url: https://testnet.api.axelarscan.io/validator/searchVMPolls
  address: axelar1gc40fw08ee4vamhvtgcszladfsrd8tyhc75l3j
  flow:
    version: v0.1.1
  xrplevm:
    version: v0.1.1
  plume:
    version: v0.1.1
  monad:
    version: v0.1.1
  berachain:
    version: v0.1.1
  hyperliquid:
    version: v0.1.1
  hedera:
    version: v0.1.1
  sui:
    version: v0.1.1
  xrpl:
    version: v0.1.1
  stellar:
    version: v0.1.1
  solana:
    version: v0.1.6
