---
- name: Set up ampd
  hosts: all
  become: true
  gather_facts: true
  vars:
    allowed_node_types: [ampd]
  vars_files:
    - group_vars/all.yml
  pre_tasks:
    - name: Load environment variables
      ansible.builtin.include_vars:
        file: "group_vars/{{ env }}.yml"
    - name: Load vault variables
      community.sops.load_vars:
        file: group_vars/vault.yml
    - name: Include environment setup tasks
      when: type in allowed_node_types
      ansible.builtin.include_tasks: tasks/setup_environment.yml
  tasks:
    - name: Setup environment and run bridge role
      when: type in allowed_node_types
      block:
        - name: Include common handlers
          ansible.builtin.include_role:
            name: common
        - name: Include ampd role
          ansible.builtin.include_role:
            name: ampd
