---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    amplifier:
      hosts:
        amplifier_tofnd_host:
          ansible_host: amplifier.axelar.mainnet.encapsulate.xyz
          type: tofnd
        amplifier_ampd_host:
          ansible_host: amplifier.axelar.mainnet.encapsulate.xyz
          type: ampd
        amplifier.axelar.mainnet.encapsulate.xyz:
