---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    amplifier:
      hosts:
        ts.tofnd.amplifier.axelar.mainnet.encapsulate.xyz:
          type: tofnd
        ts.amplifier.axelar.mainnet.encapsulate.xyz:
          type: ampd
