---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    amplifier:
      hosts:
        amplifier_tofnd_host:
          ansible_host: amplifier.axelar.testnet.encapsulate.xyz
          type: tofnd
        amplifier_ampd_host:
          ansible_host: amplifier.axelar.testnet.encapsulate.xyz
          type: ampd
    axelar:
      hosts:
        axelar_vald_host:
          ansible_host: validator.axelar.testnet.encapsulate.xyz
          type: vald
          vald_axelar_home: /opt/axelar
        axelar_tofnd_host:
          ansible_host: validator.axelar.testnet.encapsulate.xyz
          type: tofnd
