---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    amplifier:
      hosts:
        143.110.191.217:
          type: tofnd
        142.110.191.217:
          type: tofnd
