---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    amplifier:
      hosts:
        tofnd.amplifier.axelar.testnet.encapsulate.xyz:
          type: tofnd
        amplifier.axelar.testnet.encapsulate.xyz:
          type: ampd
