---
# Maintains directories and paths
vald_home_dir: "{{ vald_axelar_home }}"

vald_bin_dir: "{{ vald_home_dir }}/bin"
vald_env_dir: "{{ vald_home_dir }}/environment"
vald_vald_dir: "{{ vald_home_dir }}/vald"
vald_log_dir: "{{ vald_home_dir }}/log"

vald_directories:
  - "{{ vald_vald_dir }}"

vald_log_file_path: "{{ vald_log_dir }}/{{ service_identifier }}.log"

vald_environment_secrets_file_path: "{{ vald_env_dir }}/{{ vald_environment_secrets_file_name }}"
vald_environment_wasmvm_file_path: "{{ vald_env_dir }}/{{ vald_environment_wasmvm_file_name }}"
