---
# Maintains directories and paths
vald_home_dir: /opt/{{ service_identifier }}

vald_bin_dir: "{{ vald_home_dir }}/bin"
vald_env_dir: "{{ vald_home_dir }}/env"
vald_log_dir: "{{ vald_home_dir }}/log"

vald_directories:
  - "{{ vald_home_dir }}"
  - "{{ vald_bin_dir }}"
  - "{{ vald_env_dir }}"
  - "{{ vald_log_dir }}"

vald_log_file_path: "{{ vald_log_dir }}/{{ service_identifier }}.log"
vald_environment_secrets_file_path: "{{ vald_env_dir }}/{{ vald_environment_secrets_file_name }}"
